/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as OverlayCenaRouteImport } from './routes/overlay/cena'
import { Route as OverlayTop3RouteImport } from './routes/overlay/top3'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlayCenaRoute = OverlayCenaRouteImport.update({
  id: '/overlay/cena',
  path: '/overlay/cena',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlayTop3Route = OverlayTop3RouteImport.update({
  id: '/overlay/top3',
  path: '/overlay/top3',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/overlay/cena': typeof OverlayCenaRoute
  '/overlay/top3': typeof OverlayTop3Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/overlay/cena': typeof OverlayCenaRoute
  '/overlay/top3': typeof OverlayTop3Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/overlay/cena': typeof OverlayCenaRoute
  '/overlay/top3': typeof OverlayTop3Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/overlay/cena' | '/overlay/top3'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/overlay/cena' | '/overlay/top3'
  id: '__root__' | '/' | '/admin' | '/overlay/cena' | '/overlay/top3'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  OverlayCenaRoute: typeof OverlayCenaRoute
  OverlayTop3Route: typeof OverlayTop3Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay/cena': {
      id: '/overlay/cena'
      path: '/overlay/cena'
      fullPath: '/overlay/cena'
      preLoaderRoute: typeof OverlayCenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay/top3': {
      id: '/overlay/top3'
      path: '/overlay/top3'
      fullPath: '/overlay/top3'
      preLoaderRoute: typeof OverlayTop3RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  OverlayCenaRoute: OverlayCenaRoute,
  OverlayTop3Route: OverlayTop3Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
